
_target_: src.model.mf_lightning.MFModel
model:
  _target_: src.model.mf_model.MatrixFactorizaiton
  user_size: 6040
  item_size: 3706
  emb_dim: 256
  dropout: 0.4

criterion:
  _target_: torch.nn.MSELoss
  reduction: none

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  weight_decay: 0.1

scheduler:
  _target_: src.utils.scheduler.LRCosineScheduler
  _partial_: true
  warmup_steps: 190
  cycle_steps: 380
  cycle_mult: 2
  max_lr: 0.2
  min_lr: 0.00005
  gamma: 0.3

train_metrics:
  ${metrics.train_metrics}
val_metrics:
  ${metrics.val_metrics}
test_metrics:
  ${metrics.test_metrics}