- _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}
  filename: "epoch_{epoch:02d}-{val_recall_100:.3f}-{val_loss:.3f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 1
  auto_insert_metric_name: True
  save_weights_only: False

- _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step

- _target_: lightning.pytorch.callbacks.TQDMProgressBar
  leave: false
  refresh_rate: 20
